##### 2025.04.30 데이터베이스프로그래밍 3강 ko36 조유은
## 리스트 (1)

- 파이썬 내장 기본 데이터형에는 리스트, 튜플, 딕셔너리 세 개는 반드시 알자.
- 하지만 모델을 학습하는데 있어서 데이터를 수치형으로 변환한 numpy array가 비교적 빠른 연산을 지원하고 메모리를 효율적으로 사용할 수 있는 큰 장점이 있다.
- 같은 데이터형 집합이라 데이터형을 체크할 필요도 없고 연산 반복에 이점이 있다.
- 또, 판다스의 dataframe을 쓰면 마치 엑셀(spreadsheet)과 같이 활용이 쉽고, 행렬 연산 처리가 쉬워서 모델 학습 데이터형으로 많이 사용된다.

In [7]:
# list ptratice

k36_a = [1, 2, 3, 4, 5]
print("=" * 50)
print(k36_a)

k36_a = [1, 2, 3, 4, "만세"]
print("=" * 50)
print("파이썬 리스트는 숫자형, 문자형을 혼합하여 사용가능")
print(k36_a)

k36_a = [1, 2, 3, 4, 5]
print("=" * 50)
print("파이썬 리스트는 배열과 같이 0~4의 첨자를 갖는다.")
for k36_i in range(5):
    print("a[", k36_i, "]=", k36_a[k36_i])

print("=" * 50)
print("파이썬 리스트는 음수 첨자를 갖는다. 순서에 주의하자.")
for k36_i in range(-5, 0, 1):
    print("a[", k36_i, "]=", k36_a[k36_i])

[1, 2, 3, 4, 5]
파이썬 리스트는 숫자형, 문자형을 혼합하여 사용가능
[1, 2, 3, 4, '만세']
파이썬 리스트는 배열과 같이 0~4의 첨자를 갖는다.
a[ 0 ]= 1
a[ 1 ]= 2
a[ 2 ]= 3
a[ 3 ]= 4
a[ 4 ]= 5
파이썬 리스트는 음수 첨자를 갖는다. 순서에 주의하자.
a[ -5 ]= 1
a[ -4 ]= 2
a[ -3 ]= 3
a[ -2 ]= 4
a[ -1 ]= 5


- print("=" * 50)을 사용하면 '='를 50 개 출력할 수 있다.
- range(5) : 0에서 4까지
- range(-5, 0, 1) : -5에서 -1까지
- index(+) : 0 1  2 3 4
- index(-) : -1 -2 -3 -4 -5  

In [2]:
# list[begin:end:step]

k36_a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print("=" * 50)
print("k36_a[2:8]는 2부터 8보다 작을 때까지\n-> 0부터 시작(2, 3, 4, 5, 6, 7)")
print(k36_a[2:8])

print("=" * 50)
print("k36_a[:4]는 처음부터 4보다 작을 때까지\n-> 0, 1, 2, 3 (주의 k36_a[4] 제외)")
print(k36_a[:4])

print("=" * 50)
print("k36_a[5:]는 5부터 끝까지")
print(k36_a[5:])

print("=" * 50)
print("k36_a[:6:3]는 처음부터 6보다 작을 때까지 3씩 증가\n-> 6은 제외")
print(k36_a[:6:3])

print("=" * 50)
print("k36_a[::3]는 처음부터 끝까지 3씩 증가")
print(k36_a[::3])

k36_a = [k36_n * 3  for k36_n in range(1, 10)]
print("=" * 50)
print("k36_a는 1...9까지 n을 뽑아내서 3을 곱한 값으로 생성")
print(k36_a)

k36_a = [k36_n * 3  for k36_n in range(1, 10) if k36_n % 2 == 0]
print("=" * 50)
print("k36_a는 1...9까지 n을 뽑아내서 2로 나눈 나머지가\n0(=짝수)인 것만 뽑아 3을 곱한 값으로 생성된다.")
print(k36_a)

k36_a[2:8]는 2부터 8보다 작을 때까지
-> 0부터 시작(2, 3, 4, 5, 6, 7)
[3, 4, 5, 6, 7, 8]
k36_a[:4]는 처음부터 4보다 작을 때까지
-> 0, 1, 2, 3 (주의 k36_a[4] 제외)
[1, 2, 3, 4]
k36_a[5:]는 5부터 끝까지
[6, 7, 8, 9, 10]
k36_a[:6:3]는 처음부터 6보다 작을 때까지 3씩 증가
-> 6은 제외
[1, 4]
k36_a[::3]는 처음부터 끝까지 3씩 증가
[1, 4, 7, 10]
k36_a는 1...9까지 n을 뽑아내서 3을 곱한 값으로 생성
[3, 6, 9, 12, 15, 18, 21, 24, 27]
k36_a는 1...9까지 n을 뽑아내서 2로 나눈 나머지가
0(=짝수)인 것만 뽑아 3을 곱한 값으로 생성된다.
[6, 12, 18, 24]


##### 2025.04.30 데이터베이스프로그래밍 3강 ko36 조유은
## 리스트 (2)

- numpy의 array 생성함수
    - arange(start, end, step) : 원하는 숫자 범위, 숫자 간격에 따른 array를 생성
    - ones(shape, dtypr, order) : 1로 채워진 array 생성
    - zeros(shape, dtypr, order) : 0으로 채워진 array 생성
    - entpy(shape, dtypr, order) : 초기화되지 않은 값으로 array 생성(쓰레기 값이 들어가 있다.)
    - _like(ex_array) : 지정된 array(=ex_array)의 shape 크기만큼 지정된 값으로 채워 array 반환
      - ones_like(ex_array)  or  zeros_like(ex_array)  or  empty_like(ex_array)

In [8]:
# numpy array list

import numpy as np

k36_data1 = [1, 2, 3, 4, 5]
print("===\n", k36_data1)
k36_arr1 = np.array(k36_data1)
print("===\n", k36_arr1)
print("===\n", k36_arr1.shape)

===
 [1, 2, 3, 4, 5]
===
 [1 2 3 4 5]
===
 (5,)


- numpy를 이용하여 array 정의
- shape : array의 형태(크기)를 알 수 있는 메서드

In [9]:
# matrix
k36_arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print("===\n", k36_arr2)
print("===\n", k36_arr2.shape)

# inimatrix
np.zeros((3, 5))

===
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
===
 (4, 3)


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

- zeros(shape, dtypr, order) : 0으로 채워진 array를 생성 $\to$ zeros((3, 5))는 3행 5열의 행렬이 생성된다.
- shape : array의 형태(크기)를 알 수 있는 메서드

In [10]:
# matrix operaation
k36_arr1 = np.array([[1, 2, 3], [4, 5, 6]])
print("===\n", k36_arr1)
k36_arr2 = np.array([[10, 11, 12], [13, 14, 15]])
print("===\n", k36_arr2)
print("===\n", k36_arr1 + k36_arr2)
print("===\n", k36_arr1 - k36_arr2)
print("===\n", k36_arr1 * k36_arr2)

===
 [[1 2 3]
 [4 5 6]]
===
 [[10 11 12]
 [13 14 15]]
===
 [[11 13 15]
 [17 19 21]]
===
 [[-9 -9 -9]
 [-9 -9 -9]]
===
 [[10 22 36]
 [52 70 90]]


- 행렬의 연산 : 각 행과 열의 값끼리 연산된다.

In [11]:
k36_arr2 = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]])
print("===\n", k36_arr2)
print("===\n", k36_arr2[0, 0])
print("===\n", k36_arr2[2, :])
print("===\n", k36_arr2[2, 3])
print("===\n", k36_arr2[:, 3])

===
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
===
 1
===
 [ 9 10 11 12]
===
 12
===
 [ 4  8 12]


- 2차원의 array에서 인덱싱을 하기 위해서는 2개의 인자를 입력해야 한다.
- arry의 인덱스는 0부터 시작, ':'로 입력하는 경우는 모든 인덱스 범위의 값을 반환
- k36_arr2[0, 0] : 0행 0열의 값을 반환 $\to$ 1
- k36_arr2[2, :] : 2행의 모든 값을 반환 $\to$ [9 10 11 12]
- k36_arr2[2, 3] : 2행 3열의 값을 반환 $\to$ 12
- k36_arr2[:, 3] : 3열의 모든 값을 반환 $\to$ [4 8 12]